#!/usr/bin/env python3

import argparse
import datetime as _dt
import json
import os
import re
import shutil
from pathlib import Path


def _kebab(s: str) -> str:
    s = s.strip().lower()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    s = re.sub(r"-+", "-", s).strip("-")
    if not s:
        raise ValueError("agent_id is empty after normalization")
    return s


def _render_template(text: str, values: dict) -> str:
    for key, value in values.items():
        text = text.replace("{{" + key + "}}", str(value))
    return text


def _copy_template_file(src: Path, dst: Path, values: dict | None = None) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    content = src.read_text(encoding="utf-8")
    if values:
        content = _render_template(content, values)
    dst.write_text(content, encoding="utf-8")


def scaffold_agent_repo(*, agent_id: str, canonical_name: str, out_dir: Path, templates_dir: Path) -> None:
    agent_id = _kebab(agent_id)

    resurrection_date = _dt.date.today().isoformat()
    values = {
        "agent_id": agent_id,
        "canonical_name": canonical_name.strip(),
        "resurrection_date": resurrection_date,
    }

    if out_dir.exists() and any(out_dir.iterdir()):
        raise RuntimeError(f"Output directory not empty: {out_dir}")

    out_dir.mkdir(parents=True, exist_ok=True)

    # Core required files
    _copy_template_file(templates_dir / "AGENTS.md", out_dir / "AGENTS.md")
    _copy_template_file(templates_dir / "BOOTSTRAP.md", out_dir / "BOOTSTRAP.md")
    _copy_template_file(templates_dir / "IDENTITY.md", out_dir / "IDENTITY.md", values=values)

    # Recommended files
    _copy_template_file(templates_dir / "HEARTBEAT.md", out_dir / "HEARTBEAT.md")
    _copy_template_file(templates_dir / "TOOLS.md", out_dir / "TOOLS.md")
    _copy_template_file(templates_dir / "MEMORY.md", out_dir / "MEMORY.md")

    # SOUL is intentionally empty: created by the agent.
    (out_dir / "SOUL.md").write_text("# SOUL.md\n\n(TBD — generated by the agent from canon.)\n", encoding="utf-8")

    # Memory layout
    canon_dir = out_dir / "memory" / "__CANON__"
    canon_dir.mkdir(parents=True, exist_ok=True)

    (canon_dir / "index.json").write_text(json.dumps({"entries": []}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    memory_dir = out_dir / "memory"
    memory_dir.mkdir(parents=True, exist_ok=True)
    (memory_dir / f"{resurrection_date}.md").write_text("---\n\n", encoding="utf-8")


def validate_agent_repo(path: Path) -> list[str]:
    required = [
        "IDENTITY.md",
        "SOUL.md",
        "AGENTS.md",
        "BOOTSTRAP.md",
        "memory/__CANON__/index.json",
    ]

    errors: list[str] = []
    for rel in required:
        if not (path / rel).exists():
            errors.append(f"Missing: {rel}")

    idx = path / "memory" / "__CANON__" / "index.json"
    if idx.exists():
        try:
            data = json.loads(idx.read_text(encoding="utf-8"))
            if not isinstance(data, dict) or "entries" not in data:
                errors.append("index.json must be an object with an 'entries' field")
        except Exception as e:  # noqa: BLE001
            errors.append(f"Invalid index.json: {e}")

    return errors


def main() -> int:
    parser = argparse.ArgumentParser(prog="bibliotalk")
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_scaffold = sub.add_parser("scaffold-agent", help="Create a new spoke repo skeleton")
    p_scaffold.add_argument("agent_id")
    p_scaffold.add_argument("--canonical-name", required=True)
    p_scaffold.add_argument("--out", default=None, help="Output dir (default: ./agents/<agent_id>)")

    p_validate = sub.add_parser("validate-agent", help="Validate a spoke repo layout")
    p_validate.add_argument("path")

    args = parser.parse_args()

    root = Path(__file__).resolve().parents[1]
    templates_dir = root / "templates"

    if args.cmd == "scaffold-agent":
        agent_id = _kebab(args.agent_id)
        out = Path(args.out) if args.out else (root / "agents" / agent_id)
        scaffold_agent_repo(agent_id=agent_id, canonical_name=args.canonical_name, out_dir=out, templates_dir=templates_dir)
        print(out)
        return 0

    if args.cmd == "validate-agent":
        path = Path(args.path)
        errs = validate_agent_repo(path)
        if errs:
            for e in errs:
                print(e)
            return 2
        print("OK")
        return 0

    raise RuntimeError("unreachable")


if __name__ == "__main__":
    raise SystemExit(main())
